export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const GENERATE_ACCOUNT_INFO = 'GENERATE_ACCOUNT_INFO'
export const SET_ASSETS = 'SET_ASSETS'
export const SET_NODE_INFO = 'SET_NODE_INFO'
export const SET_USER_INFO = 'SET_USER_INFO'
